import { init, setTheme } from './lifecycle.js';
import { saveMeta, saveCats, savePresets, releaseBrowserImages } from '../storage/persistence.js';
import { openAddPresetModal, saveNewPreset, openEditPreset, updatePreset, deletePreset } from '../features/presets/actions.js';
import { importData } from '../features/archive/import.js';
import { exportData } from '../features/archive/export.js';
import { openEdit, saveArtist, deleteArtist, openDanbooruUpdate } from '../features/artists/actions.js';
import { selectCategory, addCategory, deleteCategory } from '../features/artists/categories.js';
import { toggleBatchMode, batchSelectAll, batchDelete, batchRemoveFromCategory, openBatchCategoryModal, batchAddCategories } from '../features/artists/batch.js';
import { setViewMode, handleSearch, toggleSort, setPage, toggleCardClick } from '../features/artists/navigation.js';
export const actions = { init, setTheme, saveMeta, saveCats, savePresets, releaseBrowserImages, openAddPresetModal, saveNewPreset, openEditPreset, updatePreset, deletePreset, importData, exportData, openEdit, saveArtist, deleteArtist, openDanbooruUpdate, selectCategory, addCategory, deleteCategory, toggleBatchMode, batchSelectAll, batchDelete, batchRemoveFromCategory, openBatchCategoryModal, batchAddCategories, setViewMode, handleSearch, toggleSort, setPage, toggleCardClick };
